### PR TITLE
We should always close the browser

### PR DESCRIPTION
**Pull request by mattonem**
Remote browser or not, we should always close the browser. 
Closing the browser will actually tell the remote browser provider that the session is to be ended (logs to be consolidated and session terminated), whereas only disconnecting might keep the session hanging for no reason.

## Motivation/Description of the PR
- Description of this PR, which problem it solves
When executing Codeceptjs/Puppeteer test suite using the browserstack grid, the session hang for 15min after the test suite finished executing and logs are not properly uploaded to the plateform. 
- Resolves #issueId (if applicable).
I don't have an issue ID as I identified the bug at the same time, I fixed it.

Applicable helpers:

- [ ] WebDriver
- [X] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [X] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
No test added as it would require credentials for a remote browsers provider. 
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)
`npm test` -> 2 tests fail but they fail anyway on branch `3.x` on my system

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
cc @DavertMik

**Comment by mattonem** [comment]
Actually, I'm actually arguing with myself whether `disconnect` should be handled by the remote browser provider as a proper termination just like `close`... 
[The documentation](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#browserdisconnect) is not very clear on that point.

**Comment by DavertMik** [comment]
I don't know. I would try to use it with servers like Selenoid or Moon to check what is the right command here. 
They suggest `close` even they previously used `connect`

https://github.com/aerokube/moon-cloud-puppeteer-example/blob/master/index.js#L20

**Review by DavertMik — CHANGES_REQUESTED** [review]
@mattonem Sorry, I can't merge this. Puppeteer tests are failing. I restarted them but it didn't help. Please take a look there

**Comment by DavertMik** [comment]
Thanks! Merging!

**Pull request merged**
