### PR TITLE
#2797 +CustomLocators interface

### LINKED ISSUE #2797: TypeScript: No way to extend the LocatorOrString type for custom locators
### What are you trying to achieve?
Define and use a custom locator in TypeScript code.

### What do you get instead?
Custom locators cannot be added to the type definitions, leading to compiler errors when trying to use them in any methods with `LocatorOrString` parameters.

```bash
e2e/tests/xyz.ts:166:59 - error TS2322: Type 'string' is not assignable to type '(locator: LocatorOrString) => Locator'.

166     I.seeElement({ custom: "xyz", option: true });
```

### Details

* CodeceptJS version: 3.0.4
* TypeScript version: 4.1.3

### Proposed Solution

The way to add custom types from user code is declaration merging (as already done with the `Methods` interface). However, the types `ILocator` and `LocatorOrString` are fixed union types that cannot be extended. Therefore I suggest to add a `CustomLocators` interface that can be extended from outside and that will be used to build the `LocatorOrString` type.

Example:

```typescript
interface CustomLocators { }

type LocatorOrString = string | ILocator | Locator | CustomLocators[keyof CustomLocators];
```

The property keys used in the interface are arbitrary (only the property types will be used), but should reflect the keys used in the locator object. After that, it is possible to extend the `CustomLocators` interface:

```typescript
declare global {
    namespace CodeceptJS {
        interface CustomLocators {
            custom: { custom: string; option?: boolean };
        }
    }
}
```

### PR DESCRIPTION
**Pull request by danielrentz**
## Motivation/Description of the PR
- Resolves #2797

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
@danielrentz thanks!
do you think this change should be documented in https://github.com/codeceptjs/CodeceptJS/blob/3.x/docs/typescript.md ?

**Review by DavertMik — APPROVED** [review]

**Comment by danielrentz** [comment]
> @danielrentz thanks!
> do you think this change should be documented in https://github.com/codeceptjs/CodeceptJS/blob/3.x/docs/typescript.md ?

Sure, I will do so.

**Comment by danielrentz** [comment]
@DavertMik  Done!

**Comment by DavertMik** [comment]
Thanks!

**Pull request merged**
