### PR TITLE
Right click issue fix for Webdriver

### PR DESCRIPTION
**Pull request by suniljaiswal01**
## Motivation/Description of the PR
- Description of this PR, which problem it solves
   The PR solve the  issue of rightclick() for webdriver.

- Resolves #issueId (if applicable).
#2433, #2414, #1883

Applicable helpers:

- [X] WebDriver

## Type of change

- [X] :bug: Bug fix

## Checklist:

- [x] Tests have been added
- [] Documentation has been added (Run `npm run docs`)
- [X] Lint checking (Run `npm run lint`)
- [X] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by PeterNgTr** [comment]
I'm not quite sure if adding tests would be feasible for this function. Great to have if we could.

**Comment by suniljaiswal01** [comment]
@PeterNgTr  Test is already present here : https://github.com/suniljaiswal01/CodeceptJS/blob/rightClickFix/test/helper/webapi.js#L293-L314

Do you want me to write additional test for the same?

**Comment by DavertMik** [comment]
I'm against silently replacing native click (performed by webdriver) to emulated click (performed by a script)
what you can do here is to create method "foreRightClick", as we have forceClick which acts similarly for click

**Comment by suniljaiswal01** [comment]
Changes Done. Please check if this implementation is OK

**Comment by DavertMik** [comment]
Thank you @suniljaiswal01

**Pull request merged**
