### PR TITLE
Add return type for REST helpers

### LINKED ISSUE #2590: Type definitions are wrong for REST helper
#### What are you trying to achieve?

Use the REST helper in a typescript project

#### What do you get instead?

Typescript compile errors because the provided type definitions for the REST helper do not match the actual method signatures.

The _executeRequest method and all of the send* methods are async and return the response object, however the type definition marks them as returning void. This means that in my code using these methods if I actually try to use the response object, typescript throws an error: `Type 'void' is not assignable to type 'AxiosResponse<any>'`

In addition, the arguments for each method are all marked as being required, even though most of them are optional, which means I have to pass `undefined` for each argument to prevent typescript compiler errors. 

> Example showing both of the above issues
```ts
import { AxiosResponse } from 'axios';
const res: AxiosResponse = await this.sendPostRequest('', {});
```

```bash
helpers/steps_file.ts:46:13 - error TS2322: Type 'void' is not assignable to type 'AxiosResponse<any>'.

46       const res: AxiosResponse = await this.sendPostRequest('', {});
               ~~~

helpers/steps_file.ts:46:45 - error TS2554: Expected 3 arguments, but got 2.

46       const res: AxiosResponse = await this.sendPostRequest('', {});
                                               ~~~~~~~~~~~~~~~~~~~~~~~
```

### Details

* CodeceptJS version: 2.6.10
* NodeJS Version: 14.11.0
* Operating System: Windows 10

### PR DESCRIPTION
**Pull request by vdhpieter**
## Motivation/Description of the PR
- Description of this PR, which problem it solves
  The return type of the rest helpers was void which is incorrect. They actually return the Axios response object
- Resolves #2590

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [x] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

I can't install detox locally for some reason which makes testing, linting... locally hard. I did notice though that the JSDoc I've written is assumably not correct but I have no clue why... If somebody could help me that would be greatly appreciated!

### CODE REVIEW

**Comment by vdhpieter** [comment]
@PeterNgTr Could you approve the workflows? And check the PR :)

**Comment by PeterNgTr** [comment]
Thanks @vdhpieter

**Review by PeterNgTr — APPROVED** [review]

**Review by Arhell — APPROVED** [review]

**Comment by vdhpieter** [comment]
@PeterNgTr will these be merged in soon?

**Comment by PeterNgTr** [comment]
I guess it has enough 2 approvals. I can merge now

**Pull request merged**
