### PR TITLE
fix: rest helper steps are ignored

### PR DESCRIPTION
**Pull request by PeterNgTr**
## Motivation/Description of the PR
- Currently, the `send*` steps of REST helper is added as defaultIgnoredSteps, that prevents users from using this plugin with REST helper. This PR adds the possibility to alter the `defaultIgnoredSteps` list.

Applicable helpers:

- [x] REST

Applicable plugins:

- [x] retryFailedStep

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by DavertMik** [comment]
well, this was intentional. 
for instance, you may send an invalid data to a backend and receive an error. Why would you need to retry the same request again and again?

**Comment by DavertMik** [comment]
well, this was intentional. 
for instance, you may send an invalid data to a backend and receive an error. Why would you need to retry the same request again and again?

**Comment by PeterNgTr** [comment]
So there is case on CI, the communication is dropping when making the api call. So we want to retry the call.

**Comment by DavertMik** [comment]
> So there is case on CI, the communication is dropping when making the api call. So we want to retry the call.

Use manual retry for this:

```
I.retry().send
```

**Comment by PeterNgTr** [comment]
Yeah, I know @DavertMik but the steps are randomly failed, I'm not adding to all of the steps, tho.

**Comment by PeterNgTr** [comment]
so another approach @DavertMik . This PR adds the possibility to alter the defaultIgnoredSteps list.

**Comment by DavertMik** [comment]
Sorry, this approach is overcomplicated.
I don't think anyone will understand how to use that

**Pull request closed without merging**
