### PR TITLE
DOCS(#2982) allure createStep public API description

### PR DESCRIPTION
**Pull request by EgorBodnar**
## Motivation/Description of the PR
- Description of the missed allure plugin public API `createStep`
- Clarifying issue #2982

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [X] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [x] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [X] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
@EgorBodnar sorry, didn't get question. Write to me in Slack, I will try to answer there.

I would really love to see it working like this:

```js
allure.createStep('I do something important', () => {
  I.amOnPage('/');
  I.click('Important link');
  // ....
})
```

So to wrap CodeceptJS actions into the allure step. Do you think it is possible?

**Comment by EgorBodnar** [comment]
@DavertMik added the required option, but also left the old one. 
Here is an example when why it is necessary:
https://github.com/EgorBodnar/rest-axios-codeceptjs-allure-docker-test-example/blob/main/utils/HttpService.ts
The built-in functionality of the concepts is not enough for me to make backend requests and test them, so I use Axios. Codeceptjs  acts as a test runner and as an aggregator of integration plugins, reports (allure, TestRail etc.)

**Comment by EgorBodnar** [comment]
@DavertMik Yes, that's right.
In my example(github link), just the implementation of the helper through which I send requests.

**Comment by EgorBodnar** [comment]
I think I'll add typing in another PR. If everything is ok with this PR, can we merge it?

**Comment by EgorBodnar** [comment]
> @EgorBodnar sorry, didn't get question. Write to me in Slack, I will try to answer there.
> 
> I would really love to see it working like this:
> 
> ```js
> allure.createStep('I do something important', () => {
>   I.amOnPage('/');
>   I.click('Important link');
>   // ....
> })
> ```
> 
> So to wrap CodeceptJS actions into the allure step. Do you think it is possible?

Nope.
At least at BDD tests it doesn't work properly.  
The hierarchy is not respected and step chaos ensues.

**Pull request merged**
