### PR TITLE
Adding the code to connect to sauce labs using a sauce tunnel when testing an app

### PR DESCRIPTION
**Pull request by gurjeetbains**
…sting an app

## Motivation/Description of the PR
- Description of this PR, which problem it solves
-  This PR fixes the problem if some one has to connect to sauce labs via the tunnel to test the app (Android & IOS)
- Resolves #issueId (if applicable).

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [*] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [*] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by DavertMik** [comment]
@gurjeetbains please mention this in helper's docs and I'm merging

**Comment by gurjeetbains** [comment]
> @gurjeetbains please mention this in helper's docs and I'm merging

@DavertMik Should I raise a new PR and where should I update in the repo so that it updates in site as well. I have to do for playwright docs as well

**Comment by DavertMik** [comment]
No, just add a few lines in a docblock section of Appium.js where we have confguration docs:

https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Appium.js#L43

And example configuration with a tunnel is also nice to have here:

https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Appium.js#L111

**Comment by DavertMik** [comment]
@gurjeetbains I'm merging but please raise new PR for documentation

**Pull request merged**
