### PR TITLE
Implements playwright persistent context

### PR DESCRIPTION
**Pull request by brunoqueiros**
## Motivation/Description of the PR
- Implements `launchPersistentContext` to be able to launch in Normal mode
- Resolves https://github.com/codeceptjs/CodeceptJS/issues/2376.

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [x] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [x] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [x] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks, @brunoqueiros  Seems really good! 
Probably it should be documented somewhere, right?

**Comment by brunoqueiros** [comment]
@DavertMik isn't the helpers' config created by running `npm run docs`? Or am I missing something?

https://github.com/codeceptjs/CodeceptJS/pull/2817/files#diff-5dc6e0a9028f00d161e530bc3b734e92d0497c131429e67b07e87a9224e4ecdaR150

**Comment by DavertMik** [comment]
@brunobg  This is correct
The documentation is taken from docblock comments of this source code.
So you should put your cnages to docblock of a class in PLaywright.js file

**Comment by DavertMik** [comment]
Ok, I got it, the example in helper was updated so I can merge it!

**Pull request merged**
