### PR TITLE
Fix: Fail "helper.saveScreenshot is not a function" on stepByStepReport plugin

### PR DESCRIPTION
**Pull request by andrerleao**
## Motivation/Description of the PR
- Description of this PR, which problem it solves

In the changes to remove the REST helper from list supoortedHelpers, we added this bug :'(

In the autoDelay.js file, the supoortedHelpers variable is declared by reference.

If a variable by reference is changed, all other plug-ins will have their values ​​changed as well, so by adding REST helper to the autoDelay.js file, the plugin, stepByStepReport.js will have 'REST' as well.

In this PR we changed the declaration of the variable to be by value, so we changed the list only in this plugin.

The fail "helper.saveScreenshot is not a function" occur when we use simultaneous:
 - helpers [REST, WebDriver]
 - plugins [autoDelay, stepByStepReport]

Original message fail: <Can't save step screenshot: TypeError: helper.saveScreenshot is not a function> undefined.

Related #2508,  #2513, #2527 

Applicable helpers:

- [x] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [x] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [x] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [x] screenshotOnFail
- [ ] selenoid
- [x] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [x] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by andrerleao** [comment]
@DavertMik, @PeterNgTr, Hello I reopened this PR, Please reconsider this.

**Review by PeterNgTr — DISMISSED** [review]

**Comment by DavertMik** [comment]
No, slice is too magical to me.
Looks like standardActingHelper is a way broken here.
Probably we should split it up to contain only browser helpers. Then we won't need that patches

**Comment by andrerleao** [comment]
> No, slice is too magical to me.
> Looks like standardActingHelper is a way broken here. 
   
> Probably we should split it up to contain only browser helpers. Then we won't need that patches

Hi @DavertMik, 

In PR "https://github.com/codeceptjs/CodeceptJS/pull/2513/commits/9dcf3fc8c3187e2e1d461d39ff5ef4e32c0b2155", we added this bug, when we removed the REST helper from "lib / plugin / standardActingHelpers.js", we have only browser helpers in this file.

however, In the autoDelay.js file, the supoortedHelpers variable is declared by reference, and if a variable by reference is changed, all other plug-ins will have their values ​​changed too, so by adding REST helper to the autoDelay.js file, the plugin, stepByStepReport.js will have 'REST' too, this is our problem.

To fix this problem we changed the declaration of the variable to be by value, so we can change the list only in autoDelay.js

I commited initially this change:  
const supportedHelpers = JSON.parse(JSON.stringify(require('./standardActingHelpers')));

and the @PeterNgTr is changed to, I think more clean:
const supportedHelpers = require('./standardActingHelpers').slice();

These items are related to this PR, please reconsider the change.

https://github.com/codeceptjs/CodeceptJS/issues/2508
https://github.com/codeceptjs/CodeceptJS/pull/2513
https://github.com/codeceptjs/CodeceptJS/pull/2527
https://github.com/codeceptjs/CodeceptJS/issues/2549

**Review by PeterNgTr — APPROVED** [review]

**Comment by DavertMik** [comment]
Looks like this patch was applied already somewhere in 3.x 
image
So I'm closing

**Comment by andrerleao** [comment]
> Looks like this patch was applied already somewhere in 3.x
> image
> So I'm closing

Hi, I created a new PR, i think when we rebase branchs to v3.x this commit was ignored.

**Pull request closed without merging**
